apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "daydesk.fullname" . }}-config
  labels:
    {{- include "daydesk.labels" . | nindent 4 }}
data:
  APP_BASE_URL: {{ .Values.appUrl | quote }}
  NEXTAUTH_URL: {{ .Values.appUrl | quote }}
  {{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
