{{- if not .Values.oauth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "daydesk.oauthSecretName" . }}
  labels:
    {{- include "daydesk.labels" . | nindent 4 }}
type: Opaque
stringData:
  NEXTAUTH_SECRET: {{ .Values.oauth.nextauthSecret | quote }}
  OAUTH_ISSUER: {{ .Values.oauth.issuer | quote }}
  OAUTH_CLIENT_ID: {{ .Values.oauth.clientId | quote }}
  OAUTH_CLIENT_SECRET: {{ .Values.oauth.clientSecret | quote }}
  {{- if .Values.oauth.logoutUrl }}
  OAUTH_LOGOUT_URL: {{ .Values.oauth.logoutUrl | quote }}
  {{- end }}
{{- end }}
