{{- if not .Values.auth0.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "daydesk.auth0SecretName" . }}
  labels:
    {{- include "daydesk.labels" . | nindent 4 }}
type: Opaque
stringData:
  auth0-domain: {{ .Values.auth0.domain | quote }}
  auth0-secret: {{ .Values.auth0.secret | quote }}
  auth0-client-id: {{ .Values.auth0.clientId | quote }}
  auth0-client-secret: {{ .Values.auth0.clientSecret | quote }}
{{- end }}
