{{- if not .Values.postgres.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "daydesk.postgresSecretName" . }}
  labels:
    {{- include "daydesk.labels" . | nindent 4 }}
type: Opaque
stringData:
  database-url: {{ .Values.postgres.databaseUrl | quote }}
{{- end }}
