{{- if not .Values.oauth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "daydesk.oauthSecretName" . }}
  labels:
    {{- include "daydesk.labels" . | nindent 4 }}
type: Opaque
stringData:
  oauth-issuer: {{ .Values.oauth.issuer | quote }}
  nextauth-secret: {{ .Values.oauth.nextauthSecret | quote }}
  oauth-client-id: {{ .Values.oauth.clientId | quote }}
  oauth-client-secret: {{ .Values.oauth.clientSecret | quote }}
  {{- if .Values.oauth.providerName }}
  oauth-provider-name: {{ .Values.oauth.providerName | quote }}
  {{- end }}
  {{- if .Values.oauth.logoutUrl }}
  oauth-logout-url: {{ .Values.oauth.logoutUrl | quote }}
  {{- end }}
{{- end }}
