{{- if and .Values.pushNotifications.enabled (not .Values.vapid.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "daydesk.vapidSecretName" . }}
  labels:
    {{- include "daydesk.labels" . | nindent 4 }}
type: Opaque
stringData:
  vapid-public-key: {{ .Values.vapid.publicKey | quote }}
  vapid-private-key: {{ .Values.vapid.privateKey | quote }}
  vapid-subject: {{ .Values.vapid.subject | quote }}
  push-api-secret: {{ .Values.vapid.pushApiSecret | quote }}
{{- end }}
