apiVersion: v2
name: daydesk
description: Office attendance tracker
type: application
version: 0.12.0
appVersion: "0.12.0"
home: https://github.com/kuehnleon/daydesk
sources:
  - https://github.com/kuehnleon/daydesk
maintainers:
  - name: kuehnleon
    url: https://github.com/kuehnleon
