apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  labels:
    app: {{ .Release.Name }}
type: Opaque
stringData:
  auth0-secret: {{ .Values.env.AUTH0_SECRET | quote }}
  auth0-client-id: {{ .Values.env.AUTH0_CLIENT_ID | quote }}
  auth0-client-secret: {{ .Values.env.AUTH0_CLIENT_SECRET | quote }}
